// <auto-generated />
using System;
using It.Flowy.Camunda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace It.Flowy.Camunda.Migrations
{
    [DbContext(typeof(FlowyCamundaContext))]
    [Migration("20240321114005_inizio")]
    partial class inizio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.Draft", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<long>("IdScope")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Schema")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdScope");

                    b.ToTable("Drafts", "Modelling");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.DraftTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EventAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdDraft")
                        .HasColumnType("bigint");

                    b.Property<string>("Operation")
                        .HasColumnType("longtext");

                    b.Property<string>("SchemaBackup")
                        .HasColumnType("longtext");

                    b.Property<string>("UserIdentifier")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdDraft");

                    b.ToTable("DraftTracks", "Modelling");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.Process", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BpmnProcessId")
                        .HasColumnType("longtext");

                    b.Property<long>("IdScope")
                        .HasColumnType("bigint");

                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdScope");

                    b.ToTable("Processes", "Modelling");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.Scope", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scopes", "Modelling");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.Instance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdProcess")
                        .HasColumnType("bigint");

                    b.Property<long>("Key")
                        .HasColumnType("bigint");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdProcess");

                    b.ToTable("Instances", "Processing");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.InstanceData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdInsatnce")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdInsatnce");

                    b.ToTable("InstanceDatas", "Processing");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.InstanceTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EventAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdInstance")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdInstance");

                    b.ToTable("InstanceTraks", "Processing");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.Interaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<long>("IdScope")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdScope");

                    b.ToTable("Interactions", "Processing");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.InteractionTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DataBackup")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EventAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdInteraction")
                        .HasColumnType("bigint");

                    b.Property<string>("Operation")
                        .HasColumnType("longtext");

                    b.Property<string>("UserIdentifier")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdInteraction");

                    b.ToTable("InteractionTracks", "Processing");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.Draft", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Modelling.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("IdScope")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.DraftTrack", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Modelling.Draft", "Draft")
                        .WithMany()
                        .HasForeignKey("IdDraft")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Modelling.Process", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Modelling.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("IdScope")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.Instance", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Modelling.Process", "Process")
                        .WithMany()
                        .HasForeignKey("IdProcess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.InstanceData", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Processing.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("IdInsatnce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.InstanceTrack", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Processing.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("IdInstance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.Interaction", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Modelling.Scope", "Scope")
                        .WithMany()
                        .HasForeignKey("IdScope")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("It.Flowy.Camunda.Models.Core.Processing.InteractionTrack", b =>
                {
                    b.HasOne("It.Flowy.Camunda.Models.Core.Processing.Interaction", "Interaction")
                        .WithMany()
                        .HasForeignKey("IdInteraction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });
#pragma warning restore 612, 618
        }
    }
}
